sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
cache:
  directories:
  - "$HOME/.composer/cache"
php:
- 7.0
- 7.1
- 7.2
- 7.3
env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/donden-gaeshi/
    - secure: "3lLgCMaMSBOyrKurWLr03mxtOBym0vNj/4T7fWdTvT5GTLs01k5yymsytdpC/0s4nA7ODEozIba4/XABI8Q/8z+67x5MI+1oLaOSTm5TUux8DNCUzdlA5OhB+Z9w8D4p+GAESnHL8X5R3UWMhQYVWZLQgnJZDzXm5HU/tWzQ0A4V0tln7Z+pRzoDWppSNo2fNgrLngRzvbzGMqkbc7pT6zsqVF8HiXNx8hDjUAtAYypYBpNGofxuKJ57AqFistzqqDWqv6kUXUvmmLQTk2HRpNjuv5fJgRx2Ccz2S3KXrgbFlCUArWmrsU3Ls+nzvHd/swKU2Uls3mKG9C3pH1MBT0sesIfGsf2HBoe9ICFKjmrHt3gr6AEDrEhULsHudWOOIzvapnePhTMWlvrtsLGX/dHR18TgZ+WKOOTpZb7RUDZd8Xw+PAE/XnhrQ82GvI+vInvsBhEBtylhIjhCYXVNIIqmU8d4WUYPLuEACiJczUKpnC47k/e5/pLbauyEN2dc7seAiP7hX0GbxYsN5X6rkrjHzqxlPJ4vImisNtuHNEM+thOPn7DLiGZFv9RZNcAiS6OVdIAAVpaZaC+4paYacZ5zTCqs/QbqrwICcESxt9s5WMeaEgDCzkS15qKH0CKetjtknD7DWTZhvQ6Q+CptYeBjwqJ/panf0E9ay4+T3kM="
matrix:
  include:
    - php: 7.0
      env: WP_VERSION=5.0 WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
before_script:
- composer install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
